Enable hot module reloading for webpack reporter
electrode-io/electrode-webpack-reporter pull request #13
Opened 2016-12-12 17:48 UTC by georgeweiler

This update enables hot module reloading for the electrode-webpack-reporter when changes to the app are saved. HMR is enabled via socket.io. Server code on the app is required for the socket.io connection between the reporter and the app to be established.

2016-12-12 19:46 UTC, ananavati commented on package.json
> +  "name": "gweiler-electrode-webpack-reporter",
this should be `electrode-webpack-reporter`

2016-12-12 19:49 UTC, ananavati requested changes
* lint fixes and the package name change.
* related pr in [generator-electrode](https://github.com/electrode-io/electrode/tree/master/packages/generator-electrode)

2016-12-12 23:27 UTC, georgeweiler commented
related PR: https://github.com/electrode-io/electrode/pull/66

2016-12-14 02:03 UTC, jchip commented on lib/webpack-reporter.js
> +let socketIO;
this should be an instance field of WebpackReporter.

2016-12-14 17:06 UTC, ananavati approved these changes

2016-12-14 17:59 UTC, merged